from __future__ import annotations

from pathlib import Path

from .config import load_schema_registry, load_sources, load_variable_registry
from .paths import DOCS_DIR, ROOT
from .schema import schema_summary


GENERATED_HEADER = "<!-- GENERATED BY stock-maintain docs-generate; DO NOT EDIT BY HAND. -->"
GENERATED_DOCS_DIR = DOCS_DIR / "generated"
GLOBAL_VARIABLE_DICTIONARY = ROOT / "outputs" / "variable_dictionary" / "global_variable_dictionary.xlsx"
ARCHIVE_DIR = DOCS_DIR / "99_archive" / "20260605_full_snapshot"
MAIN_DOCS = [
    "00_文档索引.md",
    "01_项目总览与阶段结论.md",
    "02_项目整体设计.md",
    "03_数据契约与命名规范.md",
    "04_基础变量与Phase2总结.md",
    "05_衍生变量Phase3总览.md",
    "06_Phase3模块设计合订本.md",
    "07_运行维护与数据字典.md",
    "08_审计验收与遗留事项.md",
    "09_Phase4启动审计与实施计划.md",
    "10_统一出口视图设计.md",
    "11_Phase4增量窗口与脚本分类.md",
    "12_Phase5验证文档交付闭环设计.md",
    "13_AgentSkill运行手册与自动报告设计.md",
    "14_运行手册.md",
]


def markdown_table(headers: list[str], rows: list[list[object]]) -> str:
    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join(["---"] * len(headers)) + " |")
    for row in rows:
        out.append("| " + " | ".join(str(value) for value in row) + " |")
    return "\n".join(out)


def render_schema_dictionary() -> str:
    registry = load_schema_registry()
    lines = [GENERATED_HEADER, "# Schema Dictionary", ""]
    for table in registry.get("tables", []):
        lines.extend(
            [
                f"## {table['name']}",
                "",
                table.get("description", ""),
                "",
                f"- Phase: `{table.get('phase', '')}`",
                f"- Primary key: `{', '.join(table.get('primary_key', []))}`",
                "",
            ]
        )
        rows = []
        for field in table.get("fields", []):
            rows.append(
                [
                    field["name"],
                    field["dtype"],
                    "no" if not field.get("nullable", True) else "yes",
                    field.get("source_api", ""),
                    field.get("source_field", field["name"]),
                    field.get("description", ""),
                ]
            )
        lines.append(markdown_table(["field", "type", "nullable", "source_api", "source_field", "description"], rows))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_variable_dictionary() -> str:
    registry = load_variable_registry()
    lines = [GENERATED_HEADER, "# Variable Dictionary", ""]
    variables = registry.get("variables", [])
    rows = []
    for item in variables:
        rows.append(
            [
                item["name"],
                item.get("label_zh", ""),
                item.get("table", ""),
                item.get("module", ""),
                item.get("tier", ""),
                item.get("source_api", item.get("source_type", "")),
                item.get("price_basis", ""),
                item.get("missing_policy", ""),
            ]
        )
    lines.append(
        markdown_table(
            ["name", "label_zh", "table", "module", "tier", "source", "price_basis", "missing_policy"],
            rows,
        )
    )
    return "\n".join(lines).rstrip() + "\n"


def render_source_dictionary() -> str:
    payload = load_sources()
    rows = []
    for api in payload.get("tushare", {}).get("apis", []):
        rows.append([api["name"], api.get("domain", ""), api.get("phase", "")])
    return "\n".join(
        [
            GENERATED_HEADER,
            "# Source API Dictionary",
            "",
            markdown_table(["api", "domain", "phase"], rows),
            "",
        ]
    )


def render_schema_summary() -> str:
    rows = [
        [row["table"], row["phase"], row["fields"], row["primary_key"], row["description"]]
        for row in schema_summary(load_schema_registry())
    ]
    return markdown_table(["table", "phase", "fields", "primary_key", "description"], rows)


def generate_docs() -> list[Path]:
    GENERATED_DOCS_DIR.mkdir(parents=True, exist_ok=True)
    outputs = {
        "generated_schema_dictionary.md": render_schema_dictionary(),
        "generated_variable_dictionary.md": render_variable_dictionary(),
        "generated_source_dictionary.md": render_source_dictionary(),
    }
    paths = []
    for name, content in outputs.items():
        path = GENERATED_DOCS_DIR / name
        path.write_text(content, encoding="utf-8")
        paths.append(path)
    return paths


def check_docs() -> list[str]:
    diffs = []
    for name in MAIN_DOCS:
        path = DOCS_DIR / name
        if not path.exists():
            diffs.append(f"missing {path}")
            continue
        if not path.read_text(encoding="utf-8").strip():
            diffs.append(f"empty {path}")
    if not ARCHIVE_DIR.exists():
        diffs.append(f"missing {ARCHIVE_DIR}")
    if not GLOBAL_VARIABLE_DICTIONARY.exists():
        diffs.append(f"missing {GLOBAL_VARIABLE_DICTIONARY}")

    expected = {
        "generated_schema_dictionary.md": render_schema_dictionary(),
        "generated_variable_dictionary.md": render_variable_dictionary(),
        "generated_source_dictionary.md": render_source_dictionary(),
    }
    if not GENERATED_DOCS_DIR.exists():
        return diffs
    for name, content in expected.items():
        path = GENERATED_DOCS_DIR / name
        if not path.exists():
            diffs.append(f"missing {path}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != content:
            diffs.append(f"stale {path}")
    return diffs
